#!/bin/zsh
set -e

#ZPrezto 
mkdir -p ~/.zprezto
cd ~/.zprezto

if [ -d .git ]; then
  git pull --recurse
else 
  git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
fi

setopt EXTENDED_GLOB
for rcfile in ~/.zprezto/runcoms/^README.md(.N); do
  ln -sfn "$rcfile" ~/.${rcfile:t}
done

# Symlink dot/* into home directory as hidden files
for f in $(ls -d ~/.dotfiles/dot/*); do ln -sfn $f ~/.$(basename $f); done

# Symlink files/* into home directory as regular files
# for f in $(ls -d ~/.dotfiles/files/*); do ln -sfn $f ~/$(basename $f); done


echo "Yeeee"